### ISSUE TITLE
Gives error even with a stable bandwidth

### ISSUE THREAD

**Issue by sjpatel21** [iTaybb/pySmartDL#24]

**Comment by sjpatel21** [comment]
Gives this error when I use pySmartDL on aws server to download some files from a very stable site.

Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 680, in post_threadpool_actions
    SmartDL_obj.retry(str(pool.get_exceptions()[0]))
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 312, in retry
    self.start()
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 300, in start
    self.wait(raise_exceptions=True)
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 452, in wait
    raise self.errors[-1]
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 680, in post_threadpool_actions
    SmartDL_obj.retry(str(pool.get_exceptions()[0]))
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 312, in retry
    self.start()
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 300, in start
    self.wait(raise_exceptions=True)
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 452, in wait
    raise self.errors[-1]
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 680, in post_threadpool_actions
    SmartDL_obj.retry(str(pool.get_exceptions()[0]))
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 312, in retry
    self.start()
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 300, in start
    self.wait(raise_exceptions=True)
  File "/usr/local/lib/python3.6/dist-packages/pySmartDL/pySmartDL.py", line 452, in wait
    raise self.errors[-1]
urllib.error.HTTPError: HTTP Error 0: The maximum retry attempts reached (The read operation timed out)

**Comment by iTaybb** [comment]
Which URL are you trying to fetch? and what OS are you trying from?

**Comment by sjpatel21** [comment]
The URL doesn't matter, as trying again with the same url successfully downloads it. 
I am using Ubuntu 18.04. 
btw if it makes any difference I am using this code to download albums from an Indian Music Streaming Site called JioSaavn.com : 
https://github.com/sjpatel21/Saavn-Downloader/blob/master/Download.py

**Comment by iTaybb** [comment]
I'm almost positive you should use the "raw" directory instead of the "blob" one.
Please try to download this:
 https://github.com/sjpatel21/Saavn-Downloader/raw/master/Download.py

**Comment by sjpatel21** [comment]
> I'm almost positive you should use the "raw" directory instead of the "blob" one.
> Please try to download this:
> https://github.com/sjpatel21/Saavn-Downloader/raw/master/Download.py

Yes, I am using the cloned version. Just shared the file to you incorrectly. Do you have any thoughts about the issue. As the error also appears when I try it on my local pc. You can see if it gets generated on your side by providing a URL like this: https://www.jiosaavn.com/featured/us-uk-top-40/aorYsyBFfFQ_

**Comment by Mrvishal2k2** [comment]
Still isn't fixed .... 
Even I face this error today...
That too with a link of just 3mb 😐 ....
