### ISSUE TITLE
RuntimeError: cannot join thread before it is started

### ISSUE THREAD

**Issue by iTaybb** [iTaybb/pySmartDL#26]
======================================================================
ERROR: test_hash (__main__.TestSmartDL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pySmartDL.py", line 65, in test_hash
    obj.wait()
  File "..\pySmartDL\pySmartDL.py", line 455, in wait
    self.post_threadpool_thread.join()
  File "C:\Python37\lib\threading.py", line 1027, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started

----------------------------------------------------------------------
Ran 9 tests in 54.065s

FAILED (errors=1)

**Comment by iTaybb** [comment]
Fixed.
