### ISSUE TITLE
RuntimeError: cannot schedule new futures after shutdown

### ISSUE THREAD

**Issue by AbirHasan2005** [iTaybb/pySmartDL#53]
**Got an error while using your pySmartDL:**
```
2022-02-09T15:19:28.538821+00:00 app[web.1]: Exception in thread Thread-5:
2022-02-09T15:19:28.538840+00:00 app[web.1]: Traceback (most recent call last):
2022-02-09T15:19:28.538858+00:00 app[web.1]: File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-02-09T15:19:28.539230+00:00 app[web.1]: self.run()
2022-02-09T15:19:28.539247+00:00 app[web.1]: File "/usr/lib/python3.8/threading.py", line 870, in run
2022-02-09T15:19:28.539522+00:00 app[web.1]: self._target(*self._args, **self._kwargs)
2022-02-09T15:19:28.539540+00:00 app[web.1]: File "/usr/local/lib/python3.8/dist-packages/pySmartDL/pySmartDL.py", line 646, in post_threadpool_actions
2022-02-09T15:19:28.539776+00:00 app[web.1]: SmartDLObj.retry(str(pool.get_exception()))
2022-02-09T15:19:28.539793+00:00 app[web.1]: File "/usr/local/lib/python3.8/dist-packages/pySmartDL/pySmartDL.py", line 341, in retry
2022-02-09T15:19:28.539941+00:00 app[web.1]: self.start()
2022-02-09T15:19:28.539957+00:00 app[web.1]: File "/usr/local/lib/python3.8/dist-packages/pySmartDL/pySmartDL.py", line 300, in start
2022-02-09T15:19:28.540098+00:00 app[web.1]: req = self.pool.submit(
2022-02-09T15:19:28.540114+00:00 app[web.1]: File "/usr/local/lib/python3.8/dist-packages/pySmartDL/utils.py", line 343, in submit
2022-02-09T15:19:28.540293+00:00 app[web.1]: future = super().submit(fn, *args, **kwargs)
2022-02-09T15:19:28.540308+00:00 app[web.1]: File "/usr/lib/python3.8/concurrent/futures/thread.py", line 179, in submit
2022-02-09T15:19:28.540443+00:00 app[web.1]: raise RuntimeError('cannot schedule new futures after shutdown')
2022-02-09T15:19:28.540498+00:00 app[web.1]: RuntimeError: cannot schedule new futures after shutdown
```

**Comment by anchit1501** [comment]
@AbirHasan2005 were you able to find any solution?
